spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/projectX?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT:d944a848a1a4e9d21445}
            client-secret: ${GITHUB_SECRET:}
            scope: user:email

  mvc:
    hiddenmethod:
      filter:
        enabled: true
petsSeller:
 default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
 remember.me.key: ${REMEMBER_ME_KEY:topsecret}

logging:
  level:
     org.hibernate.SQL: DEBUG
     org.hibernate.orm.jdbc.bind: TRACE



open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:test}
  symbols: EUR,BGN
  enabled: false


mail:
    petsSeller: "pet@seller.com"
    host: localhost
    port: 1025
    username: ${MAIL_USER:12345}
    password: ${MAIL_PASSWORD:12345}



management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"



