spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pet-seller?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT}
            client-secret: ${GITHUB_SECRET}
            scope: user:email

petsSeller:
 default.admin.pass: ${DEFAULT_ADMIN_PASS}
 remember.me.key: ${REMEMBER_ME_KEY}

logging:
  level:
     org.hibernate.SQL: DEBUG
     org.hibernate.orm.jdbc.bind: TRACE

mail:
    petsSeller: "pet@seller.com"
    host: localhost
    port: 1025
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}


management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"



